[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

# 环境变量（在Netlify UI中配置）
# DATABASE_URL = "file:./dev.db"
# JWT_SECRET = "your-secure-jwt-secret-here"
# NEXTAUTH_URL = "your-netlify-site-url"
# NEXTAUTH_SECRET = "your-nextauth-secret"

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 