[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # Context7最佳实践：为无服务器环境设置Prisma配置
  PRISMA_CLI_BINARY_TARGETS = "native,rhel-openssl-1.0.x"

# Context7推荐：预构建脚本确保数据库就绪
[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
  # Context7推荐：优化函数性能
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]
  # 函数超时时间
  timeout = 10

[dev]
  command = "npm run dev"
  port = 3000
  functions = "netlify/functions"

# Context7最佳实践：环境变量配置说明
# 在Netlify UI中配置以下环境变量：
# ================================================
# 
# DATABASE_URL = "file:/tmp/dev.db?connection_limit=1&pool_timeout=10"
# JWT_SECRET = [生成32字符随机密钥]
# NEXTAUTH_URL = "https://your-site-name.netlify.app"
# NEXTAUTH_SECRET = [生成32字符随机密钥]
# DEFAULT_USER_ID = "cmbusc9x00000x2w0fqyu591k"

# Context7修复：正确的重定向规则
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Context7最佳实践：SPA回退规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 