[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 只保留 Next.js 路由重定向，移除 API 重定向
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
