version: "3.8"

services:
  wendeal-reports:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: wendeal-reports-dev
    ports:
      - "7575:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/data/wendeal.db
      - JWT_SECRET=dev-secret-key-not-for-production
      - NEXT_TELEMETRY_DISABLED=1
      - APP_NAME=Wendeal Reports (Dev)
      - APP_URL=http://localhost:7575
      - LOG_LEVEL=debug
    volumes:
      # 持久化数据库文件
      - wendeal_dev_data:/app/data
      # 持久化上传文件
      - wendeal_dev_uploads:/app/public/uploads
      # 开发模式下挂载源代码用于热重载
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json:ro
      - ./next.config.js:/app/next.config.js:ro
      - ./tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - wendeal-dev-network
    labels:
      - "com.wendeal.service=reports"
      - "com.wendeal.env=development"

volumes:
  wendeal_dev_data:
    driver: local
    labels:
      - "com.wendeal.volume=database"
      - "com.wendeal.env=development"
  wendeal_dev_uploads:
    driver: local
    labels:
      - "com.wendeal.volume=uploads"
      - "com.wendeal.env=development"

networks:
  wendeal-dev-network:
    driver: bridge
    labels:
      - "com.wendeal.network=development"
